name: appsmuslim
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.7+3
  path_provider: ^1.3.0
  provider: ^3.1.0+1
  font_awesome_flutter: ^8.5.0
  shimmer: ^1.0.1
  tuple: ^1.0.3
  audioplayers: ^0.13.5
  share: ^0.6.3+4
  http: ^0.12.0+3
  intl: ^0.16.1
  geolocator: ^5.1.5
  queries: ^0.1.14
  flutter_local_notifications: ^1.4.0
  hijri: ^0.2.5
  flutter_compass: ^0.4.1
  scrollable_positioned_list: ^0.1.3
  google_sign_in: ^4.4.1
  firebase_auth: ^0.16.0
  oauth2: ^1.5.0
  flutter_launcher_icons: ^0.7.5 
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/splash.png" 

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/quran-data/chapters/chapters.en.json
   - assets/quran-data/chapters/chapters.id.json
   - assets/quran-data/juz.json
   - assets/quran-data/listkitab.json
   - assets/quran-data/listhadist.json
   - assets/quran-data/listbab.json
   - assets/quran-data/translations/id.indonesian.db
   - assets/quran-data/translations/en.sahih.db
   - assets/quran-data/quran-uthmani.db
   - assets/quran-data/translations.db

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay-Ultralight.ttf
          weight: 200
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
